# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Super-Linter
      uses: github/super-linter@v4.2.2
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        VALIDATE_ARM: false
        VALIDATE_POWERSHELL: false
    
    
